### ISSUE TITLE
Importing package: google_mobile_ads.dart

### ISSUE THREAD

**Issue by Tezza27** [googlecodelabs/admob-inline-ads-in-flutter#6]
When I add

import 'package:google_mobile_ads/google_mobile_ads.dart';

I get the following error:

Target of URI doesn't exist: 'package:google_mobile_ads/google_mobile_ads.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

**Comment by kunny** [comment]
Did you run `packages get` after you added `google_mobile_ads` package?

**Comment by Tezza27** [comment]
Yes, I did. I then ran flutter clean and then closed an restarted VScode, but the same arror message persists.

**Comment by kunny** [comment]
Hmm that's interesting. Could you try importing the `complete` project on your end? I'm on Android Studio and confirmed working without any issue.

I strongly believe it's more an environment issue rather than the project. You may want to check out this [stack overflow](https://stackoverflow.com/questions/44909653/visual-studio-code-target-of-uri-doesnt-exist-packageflutter-material-dart) post.

**Comment by langhoangal** [comment]
I got the same issue when using Pubspec Assist extension. I swear that I did see the package get process but somehow got into the same issue. What I did is run Pubspec Assist again to get google_mobile_ads then everything got solved.

**Comment by phiasco12** [comment]
Having the same issue here!
